#include "HL_pinmux.h"

void pinmux_init(void) {
  // unlock changing pinmux
  pinMuxReg->KICKER0 = 0x83E70B13U;
  pinMuxReg->KICKER1 = 0x95A4F1E0U;

  pinMuxReg->PINMUX[0] = PINMUX_BALL_N19_MII_RX_ER;
  pinMuxReg->PINMUX[19] = PINMUX_BALL_C1_GIOA_2 | PINMUX_BALL_E1_GIOA_3;
  pinMuxReg->PINMUX[20] = PINMUX_BALL_F2_DCAN4TX | PINMUX_BALL_W10_DCAN4RX;
  pinMuxReg->PINMUX[21] =
      PINMUX_BALL_R2_MII_TXD_2 | PINMUX_BALL_F3_MII_COL | PINMUX_BALL_G3_MDIO;
  pinMuxReg->PINMUX[22] = PINMUX_BALL_G19_MII_RXD_2;
  pinMuxReg->PINMUX[23] = PINMUX_BALL_V5_MDCLK;
  pinMuxReg->PINMUX[24] = PINMUX_BALL_H19_MII_TXEN;
  pinMuxReg->PINMUX[25] = PINMUX_BALL_H18_MII_RXD_3;
  pinMuxReg->PINMUX[26] = PINMUX_BALL_J19_MII_TXD_1;
  pinMuxReg->PINMUX[27] = PINMUX_BALL_J18_MII_TXD_0;
  pinMuxReg->PINMUX[28] = PINMUX_BALL_K18_N2HET1_00;
  pinMuxReg->PINMUX[30] =
      PINMUX_BALL_E18_MII_TXD_3 | PINMUX_BALL_D19_MII_TX_CLK;
  pinMuxReg->PINMUX[31] = PINMUX_BALL_B4_MII_CRS;
  pinMuxReg->PINMUX[33] = PINMUX_BALL_P1_MII_RXD_0;
  pinMuxReg->PINMUX[34] = PINMUX_BALL_A14_MII_RXD_1 |
                          PINMUX_BALL_K19_MII_RXCLK | PINMUX_BALL_B11_MII_RX_DV;
  pinMuxReg->PINMUX[35] = PINMUX_BALL_D3_MIBSPI2NCS_1 |
                          PINMUX_BALL_D2_MIBSPI2SOMI |
                          PINMUX_BALL_D1_MIBSPI2SIMO;
  pinMuxReg->PINMUX[36] =
      PINMUX_BALL_T4_MII_RX_AVCLK4 | PINMUX_BALL_U7_MII_TX_AVCLK4;
  pinMuxReg->PINMUX[37] =
      PINMUX_BALL_E2_MIBSPI2CLK | PINMUX_BALL_N3_MIBSPI2NCS_0;
  pinMuxReg->PINMUX[83] = SIGNAL_GIOA_0_A5;
  pinMuxReg->PINMUX[84] =
      SIGNAL_GIOA_1_C2 | SIGNAL_GIOA_2_C1 | SIGNAL_GIOA_3_E1 | SIGNAL_GIOA_4_A6;
  pinMuxReg->PINMUX[87] = SIGNAL_MDIO_G3;
  pinMuxReg->PINMUX[89] = SIGNAL_MII_COL_F3 | SIGNAL_MII_CRS_B4;
  pinMuxReg->PINMUX[90] = SIGNAL_MII_RX_DV_B11 | SIGNAL_MII_RX_ER_N19 |
                          SIGNAL_MII_RXCLK_K19 | SIGNAL_MII_RXD_0_P1;
  pinMuxReg->PINMUX[91] = SIGNAL_MII_RXD_1_A14 | SIGNAL_MII_RXD_2_G19 |
                          SIGNAL_MII_RXD_3_H18 | SIGNAL_MII_TX_CLK_D19;
  pinMuxReg->PINMUX[160] &= PINMUX_ETHERNET_MASK;

  // lock pin mux
  pinMuxReg->KICKER0 = 0x00000000U;
  pinMuxReg->KICKER1 = 0x00000000U;
}
